name: uploader
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  exif: ^3.3.0
  equatable: ^2.0.7
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
